import React, { useState, useEffect, useContext, forwardRef } from 'react'
import { Link } from 'react-router-dom'
import { GlobalState } from '../../GlobalState'
import AdDetails from './AdDetails'
import Title from '../utilities/Title'
import { Container, Row, Col, Modal, Button, FormGroup } from 'react-bootstrap'
import { TableContainer, Table, TableHead, TableBody, TableRow, TableCell, Paper } from '@material-ui/core'
import { makeStyles } from '@material-ui/core/styles'
import AdminUProf from './AdminUProf'

